import 'package:freezed_annotation/freezed_annotation.dart';

part 'github_repository_details.freezed.dart';
part 'github_repository_details.g.dart';

@freezed
sealed class GithubRepositoryDetails with _$GithubRepositoryDetails {
  const factory GithubRepositoryDetails({
    required int id,
    required String nodeId,
    required String name,
    required String fullName,
    required bool private,
    required String? description,
    required bool fork,
    required String? homepage,
    required String? language,
    required int size,
    required String defaultBranch,
    required String htmlUrl,
    required String apiUrl,
    required String gitUrl,
    required String sshUrl,
    required String cloneUrl,
    required String svnUrl,
    required String forksUrl,
    required String keysUrl,
    required String collaboratorsUrl,
    required String teamsUrl,
    required String hooksUrl,
    required String issueEventsUrl,
    required String eventsUrl,
    required String assigneesUrl,
    required String branchesUrl,
    required String tagsUrl,
    required String blobsUrl,
    required String gitTagsUrl,
    required String gitRefsUrl,
    required String treesUrl,
    required String statusesUrl,
    required String languagesUrl,
    required String stargazersUrl,
    required String contributorsUrl,
    required String subscribersUrl,
    required String subscriptionUrl,
    required String commitsUrl,
    required String gitCommitsUrl,
    required String commentsUrl,
    required String issueCommentUrl,
    required String contentsUrl,
    required String compareUrl,
    required String mergesUrl,
    required String archiveUrl,
    required String downloadsUrl,
    required String issuesUrl,
    required String pullsUrl,
    required String milestonesUrl,
    required String notificationsUrl,
    required String labelsUrl,
    required String releasesUrl,
    required String deploymentsUrl,
    required DateTime createdAt,
    required DateTime updatedAt,
    required DateTime pushedAt,
    required int stargazersCount,
    required int watchersCount,
    required int forksCount,
    required int forks,
    required int openIssuesCount,
    required int openIssues,
    required int watchers,
    required int networkCount,
    required int subscribersCount,
    required bool hasIssues,
    required bool hasProjects,
    required bool hasDownloads,
    required bool hasWiki,
    required bool hasPages,
    required bool hasDiscussions,
    required bool archived,
    required bool disabled,
    String? mirrorUrl,
    String? license,
    String? tempCloneToken,
  }) = _GithubRepositoryDetails;

  factory GithubRepositoryDetails.fromJson(Map<String, dynamic> json) =>
      _$GithubRepositoryDetailsFromJson(json);
}
